/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Homepage;

import Admin.stud_info_dsp;
import database.database;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Yohannes
 */
public class displat_teach_info extends javax.swing.JFrame {
    database db = new database();
    String DBName = db.dbnm.getText();
    String DBUser = db.dbusr.getText();
    String DBPass = db.pass.getText();
    
    String s,g;
    String load;
    String w1= null,w2= null,w3 = null,w4= null,w5= null,w6 = null;
    int x,r,e;
    int temp;
    
    Connection con =null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    private static displat_teach_info obj = null;
    
    public displat_teach_info() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            ShowTable();
        } catch (SQLException ex) {
            Logger.getLogger(displat_teach_info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static displat_teach_info getobj()
    {
        if(obj==null)
        {
            obj = new displat_teach_info();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable1.setBackground(new java.awt.Color(204, 0, 0));
        jTable1.setFont(new java.awt.Font("AbnetZeMelakt", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        teach_info tdsp = new teach_info();
        tdsp.getobj().setVisible(true);
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        int column = source.columnAtPoint( evt.getPoint() );
        String s=source.getModel().getValueAt(row, column)+"";
        try {
            //connection
            con = DriverManager.getConnection(DBName,DBUser,DBPass);
            String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15;
            load = "SELECT id,Name,fathername,techinfo,sex,phoneno,personphoto FROM techregst WHERE id=?";
            ps = con.prepareStatement(load);
            ps.setString(1, s);
            rs=ps.executeQuery();
            while(rs.next())
            {
                this.setVisible(false);
                s1 = rs.getString(1);
                s2 = rs.getString(2);
                s3 = rs.getString(3);
                s4 = rs.getString(4);
                s5 = rs.getString(5);
                s6 = rs.getString(6);
                s7 = rs.getString(7);
                

                tdsp.getobj().jTextField18.setText(s1);
                tdsp.getobj().jTextField7.setText(s2);
                tdsp.getobj().jTextField8.setText(s3);
                tdsp.getobj().jTextArea2.setText(s4);
                tdsp.getobj().jTextField9.setText(s5);
                tdsp.getobj().jTextField13.setText(s6);
                
                byte[] imgbyt;
                Image img;
                imgbyt = rs.getBytes(7);
                img = getToolkit().createImage(imgbyt);
                Image im = img.getScaledInstance(tdsp.getobj().jLabel3.getWidth(), tdsp.getobj().jLabel3.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(im);
                tdsp.getobj().jLabel3.setIcon(icon);
            }
        } catch (SQLException ex) {
            System.out.print(ex);
    }
    }//GEN-LAST:event_jTable1MouseClicked
    public void ShowTable() throws SQLException{
        con = DriverManager.getConnection(DBName,DBUser,DBPass);
        String str = "SELECT id,Name,fathername,age,sex,phoneno FROM techregst";
        ps=con.prepareStatement(str);
        rs=ps.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displat_teach_info().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
